In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('diabetes.csv')
df.head()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X=df.iloc[:,0:9]
y=df.iloc[:,-1]
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X=ss.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
X_train,X_test

(array([[ 0.93691372,  0.91091809,  0.45982725, ...,  0.66479969,
          1.76634642,  1.36589591],
        [ 0.04601433, -0.74783062, -0.47073225, ..., -0.08720986,
         -0.95646168, -0.73212021],
        [-1.14185152,  1.38037527,  1.08020025, ..., -0.13553176,
         -0.87137393, -0.73212021],
        ...,
        [ 0.04601433, -0.84172205, -0.2122435 , ..., -0.97814487,
         -1.04154944, -0.73212021],
        [ 2.12477957, -1.12339636,  0.25303625, ..., -0.51908683,
          0.14967911, -0.73212021],
        [ 0.3429808 ,  0.47275805,  0.66661825, ...,  0.50775352,
          3.04266271, -0.73212021]]),
 array([[-0.84488505,  2.44447821,  0.35643175, ...,  2.784923  ,
         -0.95646168,  1.36589591],
        [-0.54791859, -0.43485916,  0.25303625, ..., -0.20499449,
         -0.87137393, -0.73212021],
        [ 0.04601433, -1.40507067, -0.36733675, ..., -0.24425603,
         -0.70119842, -0.73212021],
        ...,
        [ 0.04601433,  0.66054092,  0.87340925, ...,  

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

1.0

In [ ]:
lr.coef_

array([-4.12414717e-17,  3.33066907e-16, -6.24500451e-17, -3.46944695e-17,
        3.22658567e-16, -2.17382536e-16, -2.06432094e-16,  2.77555756e-17,
        4.76640761e-01])

In [ ]:
lr.intercept_

0.3489583333333331

# **Multiple Linear Regression From Scratch**

In [ ]:
class MLR:
  def __init__(self):
    self.coef_=None
    self.intercept_=None
  def fit(self,X_train,y_train):
    if isinstance(X_train, pd.DataFrame) or isinstance(X_train, pd.Series):
            X_train = X_train.to_numpy()
    if isinstance(y_train, pd.DataFrame) or isinstance(y_train, pd.Series):
            y_train = y_train.to_numpy()
    X_train=np.insert(X_train,0,1,axis=1)
    beta=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.coef_=beta[1:]
    self.intercept_=beta[0]

  def predict(self,X_test):
    y=np.dot(X_test,self.coef_)+self.intercept_
    return y

In [ ]:
M=MLR()
M.fit(X_train,y_train)
y_pred=M.predict(X_test)
r2_score(y_test,y_pred)

1.0

In [ ]:
M.coef_

array([-5.89805982e-17, -3.57353036e-16,  4.16333634e-17,  2.25514052e-17,
        3.20923843e-17, -1.00613962e-16,  2.16840434e-18, -4.16333634e-17,
        4.76640761e-01])

In [ ]:
M.intercept_

0.34895833333333337