In [293]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import random
from sklearn.datasets import make_regression

In [309]:
X,y=make_regression(n_samples=150,n_features=3,n_informative=3,n_targets=1,noise=40,random_state=42)

In [310]:
X.shape


(150, 3)

In [311]:
y.shape

(150,)

In [312]:
from sklearn.linear_model import Ridge
ridge1=Ridge(alpha=10)
ridge1.fit(X,y)
print(ridge1.coef_)
ridge1.intercept_


[44.78710734 64.81962757 80.45173584]


-2.6681171919911386

In [313]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X,y)
print(lr.coef_)
lr.intercept_

[48.02271369 69.48236745 87.66279047]


-3.232721446941935

In [314]:
from sklearn.linear_model import Ridge
ridge=Ridge(alpha=100)
ridge.fit(X,y)
print(ridge.coef_)
ridge.intercept_


[27.81314949 40.53785471 46.17016259]


0.02008577485244656

In [317]:
class Ridge:
  def __init__(self,alpha=0):
    self.alpha=alpha
    self.coef_=None
    self.intercept_=None
  def fit(self,x_train,y_train):
    x_train=np.insert(x_train,0,1,axis=1)
    I=np.identity(x_train.shape[1])
    beta=np.linalg.inv(np.dot(x_train.T,x_train)+(self.alpha*I)).dot(x_train.T).dot(y_train)
    self.coef_=beta[1:]
    self.intercept_=beta[0]
  def predict(self,x_test):
    return (np.dot(self.coef_,x_test))+self.intercept_

In [322]:
ridge=Ridge(alpha=10)
ridge.fit(X,y)
print(ridge.coef_)
ridge.intercept_

[44.80675008 64.80623228 80.43551152]


-2.496807315197599